services:
  backend:
    container_name: rdv-backend
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - redis
    environment:
      - APP_SECRET=a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef
      - FRONTEND_URL=http://localhost
      # Optionnel
      #- SPOTIFY_CLIENT_ID=
      #- SPOTIFY_CLIENT_SECRET=
      #- SPOTIFY_REDIRECT_URI=http://localhost:3001/api/spotify/callback

  frontend:
    container_name: rdv-frontend
    build:
      context: ./frontend
      args:
        - VITE_BACKEND_URL=http://localhost:3001
        - VITE_ADMIN_PASSWORD=secret
        - VITE_APP_SECRET=a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef
        # Optionnel
        # - VITE_SPOTIFY_CLIENT_ID=2157f438f5034a325481be9b9f3f215a
    ports:
      - "80:80"

  redis:
    image: redis:latest
    container_name: rdv-redis

